### ISSUE TITLE
Training Enterance

### ISSUE THREAD

**Issue by mattxsong** [liuaohanjsj/SILC#1]
Hello there，

Thank you for open-sourcing such fantastic work!
I have been trying to train your model from scratch. 
However, I was unable to locate the training entry.
Would you kindly provide it?

Thanks.

**Comment by liuaohanjsj** [comment]
Thank you for your interest in our work! We have added the training file. Run `python train_model.py -mode x` to train the model without fine-tuning. Change the variable `version` in the code to 1 or 2 to train on IU-Xray and MIMIC-CXR accordingly. The reinforcement learning code is in the file but needs cleaning. We will provide a more formal training script soon.

**Comment by mattxsong** [comment]
Thanks
